### ISSUE TITLE
Problems while running on Github Pages

### ISSUE THREAD

**Issue by odfsoft** [stackbit-themes/fresh-nextjs#3]
Im trying to set this theme for my personal blog using github pages, but the default configuration doesnt seem to work:

Steps:
1) Checkout https://github.com/stackbithq/stackbit-theme-fresh/tree/jekyll
2) Create a new repo and place there the content of the blog
3) Try to run it locally following the steps on the README:
```
1. Install Jekyll and Bundler

        gem install jekyll bundler

1. Install dependencies from Gemfile:

        bundle install

1. Build the site and make it available on a local server

        bundle exec jekyll serve

1. Browse to [http://localhost:4000](http://localhost:4000)
```
I validated that works locally, but once pushed to master in github and github pages is enable. the page is not displayed.

I guess this is related to the `theme: ""` and `remote-theme:..` but which value should I use for `remote-theme`

sample project: https://github.com/odfsoft/odfsoft.github.io

**Comment by MuneebJS** [comment]
Any update on this?
I'm having the same issue.
Github-pages isn't able to bundle the theme and giving me the troubleshooting error.

**Comment by hcshires** [comment]
Same here

**Comment by Rubix982** [comment]
I got it to work ... I have no idea how, though. 

Check out the GitHub repository [here](https://github.com/Rubix982/ASP.NET-Core-5.0-Backend-ReactJS-Typescript-Frontend-Template/tree/main/docs).

The URL is [this](https://rubix982.github.io/ASP.NET-Core-5.0-Backend-ReactJS-Typescript-Frontend-Template/about/). There is nothing at `/` at the moment.

I also used Stackbit for [Software Development Pakistan](https://softdevpk.com/) which uses Stackbit Fresh and  Github Pages. You can find the repository for that [here](https://github.com/Software-Development-Pakistan/Software-Development-Pakistan.github.io).

**Comment by TomasBankauskas** [comment]
Hi, thank you for opening this issue, but this theme was ported to use Next.js and Git and this issue is no longer applicable.
